version: '3'
services:

  laravel:
    build: ./laravel/
    working_dir: /var/www
    ports:
        # port to laravel, after start app is available at http://localhost:port
        - 8080:8080
        # port for hot module replacement at development
        # if you change this you also need to change it at jobbar-app/webpack.mix.js
        - 8081:8081
    volumes:
        - ../jobbar-app/:/var/www
    command:
        # check install, start laravel server and compiling javascript
        # uncomment if you dont want to start it automatically
        - /run.sh
    links:
        - mysql

  mysql:
    image: mariadb
    environment:
        # if you change any credentials here, you need to adopt these in your .env file
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
    #volumes:
    #    - ./mysql:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8083:80
    links:
      - mysql:db